#!/bin/bash

cd  /home/pi/mjpg-streamer/mjpg-streamer-experimental/
sleep 2
git pull
/home/pi/mjpg-streamer/mjpg-streamer-experimental/mjpg_streamer -i "input_raspicam.so -x 640 -y 480 -fps 10 -q 80" -o "output_http.so -p 8080 -w /home/pi/mjpg-streamer/mjpg-streamer-experimental/www"


